### ISSUE TITLE
Step 1 missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by drneavin** [weizhou0/qtl#14]
I'm receiving an error in step 1 for about half of the genes I've tested so far. Any ideas on how I might be able to resolve this? Happy to provide a more extensive log file if that's helpful as well.

```
Error in if (sum(tau[2:length(tau)]) == 0) { :
  missing value where TRUE/FALSE needed
Calls: fitNULLGLMM_multiV -> system.time -> glmmkin.ai_PCG_Rcpp_multiV
Timing stopped at: 5.162 0.094 5.279
Execution halted
```

**Comment by drneavin** [comment]
I updated my the genotype file in step 1 to use just 1,000 representative SNPs as recommended in [issue 12](https://github.com/weizhou0/qtl/issues/12) which I thought might resolve this issue but I'm still running into a similar error to the one originally reported:
```
Error in if (max(abs(alpha - alpha0)/(abs(alpha) + abs(alpha0) + tol.coef)) <  : 
  missing value where TRUE/FALSE needed
Calls: fitNULLGLMM_multiV ... system.time -> glmmkin.ai_PCG_Rcpp_multiV -> Get_Coef_multiV
Timing stopped at: 0.622 0.02 0.648
```

This happens for ~15% of the genes (14/22 tested so far). I am working with a small dataset (~40 donors) so I'm wondering if it has to do with this small sample size or something else that I need to correct. Happy to provide more extensive outputs if helpful.

Thanks for your help!

**Comment by LinfengHu-1** [comment]
Hi @hnolen,

Thank you for explaining the issue! For inclusion of GRM:

- Fitting GRM during step1 option: We have just updated the code & pixi binaries on this GitHub repo (if you prefer docker we updated to wzhou88/saigeqtl:0.3.5.1 on dockerhub), after reinstallation, your command pasted before should work now by making the GRM on-the-fly!

- Sparse GRM option: User would need to construct the sparseGRM prior to running step 1, here are some references where you might find useful when creating one: https://saigegit.github.io/SAIGE-doc/docs/createSparseGRM.html. For simplicity, I'm attaching this set of example sparseGRM files needed for your step1 running here so you can directly download for test run: [testmtx.zip](https://github.com/user-attachments/files/25424541/testmtx.zip). After obtaining the sparseGRM files, the sparseGRM flag can be used like this [below commands are updated on _03/12/2026_ with critical modifications of the --userGRMtoFitNULL flag setting to TRUE that is required for GRM to be accounted for in the step1 fitting. Huge thanks to @kcybgj for noticing and bringing up this issue!!] :

```
cd SAIGEQTL/extdata/
step1_fitNULLGLMM_qtl.R \
    --useSparseGRMtoFitNULL=TRUE \
    --sparseGRMFile=./n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx \
    --sparseGRMSampleIDFile=./n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt\
    --useGRMtoFitNULL=TRUE \
    --phenoFile=./input/seed_1_100_nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_Poisson.txt \
    --phenoCol=gene_1 \
    --covarColList=X1,X2,pf1,pf2 \
    --sampleCovarColList=X1,X2 \
    --sampleIDColinphenoFile=IND_ID \
    --traitType=count \
    --outputPrefix=./output/nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_gene_1 \
    --skipVarianceRatioEstimation=FALSE \
    --isRemoveZerosinPheno=FALSE \
    --isCovariateOffset=FALSE \
    --isCovariateTransform=TRUE \
    --skipModelFitting=FALSE \
    --tol=0.02 \
    --plinkFile=./input/n.indep_100_n.cell_1 \
    --IsOverwriteVarianceRatioFile=TRUE
```

Thank you so much for providing all your logs and commands. Hopefully these are helpful!

**Comment by kcybgj** [comment]
Hi @LinfengHu-1,

I tried the commands in your “Sparse GRM option” section, but it seems that the sparse GRM was still not actually used.

In the log, I still see messages such as:
```
No GRM will be used to fit the NULL model and nThreads is set to 1
Solver method: SMW (repeated cells detected, no GRM)
```
The status.txt file is shown below:
```
=== SAIGEQTL Step 1 Analysis Status ===
Timestamp: 2026-03-13 01:12:00.268095
SAIGEQTL Version: 0.3.5.1
Convergence Status: SUCCESS
Details: Model converged successfully. Theta sum: 0.381965
Final Model File: /<hidden_path>/SAIGEQTL/nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_gene_1.rda
Variance Ratio File: /<hidden_path>/SAIGEQTL/nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_gene_1.varianceRatio.txt

=== Arguments Used ===
plinkFile: /<hidden_path>/SAIGEQTL/SAIGEQTL/extdata/input/n.indep_100_n.cell_1_01.step1
useSparseGRMtoFitNULL: TRUE
sparseGRMFile: /<hidden_path>/SAIGEQTL/testmtx/n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx
sparseGRMSampleIDFile: /<hidden_path>/SAIGEQTL/testmtx/n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt
phenoFile: /<hidden_path>/SAIGEQTL/SAIGEQTL/extdata/input/seed_1_100_nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_Poisson.txt
phenoCol: gene_1
isRemoveZerosinPheno: FALSE
sampleIDColinphenoFile: IND_ID
traitType: count
outputPrefix: /<hidden_path>/SAIGEQTL/nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_gene_1
isCovariateOffset: FALSE
nThreads: 1
useSparseGRMforVarRatio: FALSE
invNormalize: FALSE
covarColList: X1,X2,pf1,pf2
tol: 1e-05
maxiter: 20
tolPCG: 1e-05
maxiterPCG: 500
SPAcutoff: 2
numMarkersForVarRatio: 30
skipModelFitting: FALSE
skipVarianceRatioEstimation: FALSE
memoryChunk: 2
tauInit: 0,0
LOCO: TRUE
isLowMemLOCO: FALSE
traceCVcutoff: 0.0025
nrun: 30
ratioCVcutoff: 0.001
IsOverwriteVarianceRatioFile: TRUE
relatednessCutoff: 0
isCateVarianceRatio: FALSE
cateVarRatioMinMACVecExclude: 10,20.5
cateVarRatioMaxMACVecInclude: 20.5
isCovariateTransform: TRUE
isDiagofKinSetAsOne: FALSE
minMAFforGRM: 0.01
maxMissingRateforGRM: 0.15
minCovariateCount: -1
includeNonautoMarkersforVarRatio: FALSE
FemaleCode: 1
FemaleOnly: FALSE
MaleCode: 0
MaleOnly: FALSE
useGRMtoFitNULL: FALSE
sampleCovarCol: X1,X2
isStoreSigma: TRUE
isShrinkModelOutput: TRUE
isExportResiduals: FALSE
varRatioBatchSize: 1
solverMethod: auto
```
My main question is: although useSparseGRMtoFitNULL is set to TRUE and both sparseGRMFile and sparseGRMSampleIDFile are provided, why does the log still indicate that no GRM was used to fit the NULL model?

Is there any additional argument that needs to be set, or could this be a logging issue?

Thanks very much.

> Hi [@hnolen](https://github.com/hnolen),
> 
> Thank you for explaining the issue! For inclusion of GRM:
> 
> * Fitting GRM during step1 option: We have just updated the code & pixi binaries on this GitHub repo (if you prefer docker we updated to wzhou88/saigeqtl:0.3.5.1 on dockerhub), after reinstallation, your command pasted before should work now by making the GRM on-the-fly!
> * Sparse GRM option: User would need to construct the sparseGRM prior to running step 1, here are some references where you might find useful when creating one: https://saigegit.github.io/SAIGE-doc/docs/createSparseGRM.html. For simplicity, I'm attaching this set of example sparseGRM files needed for your step1 running here so you can directly download for test run: [testmtx.zip](https://github.com/user-attachments/files/25424541/testmtx.zip). After obtaining the sparseGRM files, the sparseGRM flag can be used like this:
> 
> ```
> cd SAIGEQTL/extdata/
> step1_fitNULLGLMM_qtl.R \
>     --useSparseGRMtoFitNULL=TRUE \
>     --sparseGRMFile=./n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx \
>     --sparseGRMSampleIDFile=./n.indep_100_n.cell_1_full_sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt\
>     --useGRMtoFitNULL=FALSE \
>     --phenoFile=./input/seed_1_100_nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_Poisson.txt \
>     --phenoCol=gene_1 \
>     --covarColList=X1,X2,pf1,pf2 \
>     --sampleCovarColList=X1,X2 \
>     --sampleIDColinphenoFile=IND_ID \
>     --traitType=count \
>     --outputPrefix=./output/nindep_100_ncell_100_lambda_2_tauIntraSample_0.5_gene_1 \
>     --skipVarianceRatioEstimation=FALSE \
>     --isRemoveZerosinPheno=FALSE \
>     --isCovariateOffset=FALSE \
>     --isCovariateTransform=TRUE \
>     --skipModelFitting=FALSE \
>     --tol=0.00001 \
>     --plinkFile=./input/n.indep_100_n.cell_1 \
>     --IsOverwriteVarianceRatioFile=TRUE
> ```
> 
> Thank you so much for providing all your logs and commands. Hopefully these are helpful!

**Comment by LinfengHu-1** [comment]
Hi @kcybgj [and @hnolen for correction on previous mistakes I made when pasting the commands to run],

Thank you for following up on this GRM inclusion issue! You are definitely right, I forgot to turn --useGRMtoFitNULL back to TRUE when sharing the command to run using sparseGRM. This flag should be set to TRUE to properly account for genetic relatedness like you said, then the logging message should read as expected. I have modified the section of commands above to reflect this change.
Also, I changed --tol flag to the default 0.02 instead of any stringent number as this is just an example run, this change just makes the example data quicker to converge instead of having to increase the maximum iterations (partially because the sparseGRM files I shared above was created rather crudely and might actually need to increase the number of iterations for the model to successfully converge if setting really stringent value for --tol flag.) These parameters can be modified specifically for your data, or you can also choose to fit the full GRM.
Please let us know if you still encounter any issues. Thank you!
